spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: DEBUG               # SQL 구문을 출력
    org.hibernate.orm.jdbc.bind: TRACE       # 파라미터 바인딩 로그 출력

ai:
  service:
    url: http://localhost:8000

llama:
  base-url: http://localhost:8000   # FastAPI 주소
  history-limit: 20